<?php

namespace Tests\Feature;

use App\Domains\Documents\Transformers\DocXTransformer;
use App\Domains\Documents\Transformers\PowerPointTransformer;
use App\Models\Document;
use Illuminate\Support\Facades\Bus;
use Illuminate\Support\Facades\File;
use Tests\TestCase;

class DocXTransformerTest extends TestCase
{
    use SharedSetupForPptFile;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        //$this->markTestIncomplete('@TODO It works with a test PPTX but I might try a different approach since more complicated PPTX did not');
    }

    protected function tearDown(): void
    {
        if (! File::exists($this->document->pathToFile())) {
            File::delete($this->document->pathToFile());
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test_gets_data_from_docx()
    {
        Bus::fake();
        $this->setupFile('example.docx');
        $document = Document::factory()->docx()->create();
        $this->assertDatabaseCount('document_chunks', 0);
        $transformer = new DocXTransformer();
        $transformer->handle($this->document);
        $this->assertDatabaseCount('document_chunks', 1);

    }

    public function test_does_not_repeat()
    {
        Bus::fake();
        $this->setupFile();
        $document = Document::factory()->pptx()->create();
        $this->assertDatabaseCount('document_chunks', 0);
        $transformer = new PowerPointTransformer();
        $transformer->handle($this->document);
        $this->assertDatabaseCount('document_chunks', 5);
        $transformer->handle($this->document);
        $this->assertDatabaseCount('document_chunks', 5);
    }
}
