<?php

namespace Tests\Feature;

use App\Domains\Documents\Transformers\PdfTransformer;
use Illuminate\Support\Facades\Bus;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Tests\TestCase;

class PdfTransformerTest extends TestCase
{
    use SharedSetupForPdfFile;

    protected function tearDown(): void
    {
        if (! File::exists($this->document->pathToFile())) {
            File::delete($this->document->pathToFile());
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test_gets_data_from_pdf()
    {
        Bus::fake();
        $this->webFileDownloadSetup();
        $this->assertDatabaseCount('document_chunks', 0);
        $transformer = new PdfTransformer();
        $transformer->handle($this->document);
        $this->assertDatabaseCount('document_chunks', 72);

        $pages = 10;

        $this->assertCount(10, DB::table('document_chunks')
            ->where('section_number', 0)
            ->where('document_id', $this->document->id)
            ->get());

        Bus::assertBatchCount(1);

    }

    public function test_does_not_repeat()
    {
        Bus::fake();
        $this->webFileDownloadSetup();
        $this->assertDatabaseCount('document_chunks', 0);
        $transformer = new PdfTransformer();
        $transformer->handle($this->document);
        $this->assertDatabaseCount('document_chunks', 72);
        $transformer->handle($this->document);
        $this->assertDatabaseCount('document_chunks', 72);
    }
}
