<?php

namespace Tests\Feature;

use App\Domains\Documents\Transformers\PowerPointTransformer;
use App\Models\Document;
use Illuminate\Support\Facades\Bus;
use Illuminate\Support\Facades\File;
use Tests\TestCase;

class PowerPointTransformerTest extends TestCase
{
    use SharedSetupForPptFile;

    protected function tearDown(): void
    {
        if (! File::exists($this->document->pathToFile())) {
            File::delete($this->document->pathToFile());
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test_gets_data_from_pptx()
    {
        Bus::fake();
        $this->setupFile();
        $document = Document::factory()->pptx()->create();
        $this->assertDatabaseCount('document_chunks', 0);
        $transformer = new PowerPointTransformer();
        $transformer->handle($this->document);
        $this->assertDatabaseCount('document_chunks', 5);

        Bus::assertBatchCount(1);

    }

    public function test_does_not_repeat()
    {
        Bus::fake();
        $this->setupFile();
        $document = Document::factory()->pptx()->create();
        $this->assertDatabaseCount('document_chunks', 0);
        $transformer = new PowerPointTransformer();
        $transformer->handle($this->document);
        $this->assertDatabaseCount('document_chunks', 5);
        $transformer->handle($this->document);
        $this->assertDatabaseCount('document_chunks', 5);
    }
}
